version: "3.8"

services:
  risks-db:
    image: mysql:8.0
    container_name: risks-db
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: wallets-risk
    ports:
      - "3306:3306"
    volumes:
      - risk_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  view-db:
    image: mysql:8.0
    container_name: view-db
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: wallets-view
    ports:
      - "3307:3306"
    volumes:
      - view_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  wallets-cache:
    image: redis:7.0-alpine
    container_name: wallets-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  events-db:
    image: cassandra:4.1
    container_name: events-db
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
    environment:
      CASSANDRA_START_RPC: "true"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      retries: 5

  pulsar-broker:
    image: apachepulsar/pulsar:3.1.0
    container_name: pulsar-broker
    command: bin/pulsar standalone
    ports:
      - "6650:6650" # Pulsar broker
      - "8080:8080" # Pulsar web UI
    volumes:
      - pulsar_data:/pulsar/data
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/admin/v2/brokers/standalone",
        ]
      interval: 15s
      retries: 5

volumes:
  risk_db_data:
  view_db_data:
  redis_data:
  cassandra_data:
  pulsar_data:
